<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="657" started-at="2019-12-03T06:36:52Z" finished-at="2019-12-03T06:36:53Z">
    <groups>
      <group name="loginTrue">
        <method signature="LoginTest.LoginTrue()[pri:0, instance:com.Test.cases.LoginTest@1bb089b]" name="LoginTrue" class="com.Test.cases.LoginTest"/>
      </group> <!-- loginTrue -->
    </groups>
    <test name="Testng" duration-ms="657" started-at="2019-12-03T06:36:52Z" finished-at="2019-12-03T06:36:53Z">
      <class name="com.Test.cases.LoginTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.Test.cases.LoginTest@1bb089b]" name="beforeTest" is-config="true" duration-ms="33" started-at="2019-12-03T14:36:52Z" description="登录接口" finished-at="2019-12-03T14:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="LoginTrue()[pri:0, instance:com.Test.cases.LoginTest@1bb089b]" name="LoginTrue" duration-ms="614" started-at="2019-12-03T14:36:52Z" description="登录成功的接口" finished-at="2019-12-03T14:36:53Z">
          <exception class="org.apache.ibatis.binding.BindingException">
            <message>
              <![CDATA[Invalid bound statement (not found): com.Test.model.DBmodel.UsersMapper.selectOne]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.Test.model.DBmodel.UsersMapper.selectOne
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:225)
	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:48)
	at org.apache.ibatis.binding.MapperProxy.cachedMapperMethod(MapperProxy.java:65)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
	at com.sun.proxy.$Proxy4.selectOne(Unknown Source)
	at com.Test.cases.LoginTest.LoginTrue(LoginTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.ibatis.binding.BindingException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTrue -->
      </class> <!-- com.Test.cases.LoginTest -->
    </test> <!-- Testng -->
  </suite> <!-- Default Suite -->
</testng-results>
